blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/SacBase/vscode/blob/master/SUPPORT.md
    about: Please read support guidance before opening a new issue.
  - name: Existing issues
    url: https://github.com/SacBase/vscode/issues
    about: Search existing issues before creating a new one.
